parameters:
#    kpolis_ads.example.class: kpolis\AdsBundle\Example

services:
#    kpolis_ads.example:
#        class: %kpolis_ads.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
